"""Builder-agent orchestrator (research mode).

Standalone runbook module — *not* imported by the FastAPI app. Given a connector
spec YAML (from the extraction agent), it scaffolds a ``Connector`` subclass that
matches the framework contract, so the builder agent (or a human) only fills in
the platform-specific request/response handling.

The generated module deliberately starts as a faithful skeleton: correct class
name, capabilities, property reads, and the two abstract methods stubbed to raise
``ConnectorError("not implemented")`` — it imports and registers cleanly but is
honest that it does nothing until completed.

Usage (from the repo root)::

    python meridian/connectors/agents/builder-agent/builder.py \
        meridian/connectors/catalog/zoho/_props.zoho.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_TEMPLATE = '''\
"""{display_name} connector — SCAFFOLD (status: {status}).

Generated by the builder-agent from {source}. Fill in pull()/push() against the
documented endpoints, add a MockTransport test, then promote status to `complete`.
"""

from __future__ import annotations

from ...base import (
    Capabilities,
    ConnectionContext,
    ConnectorError,
    HTTPConnector,
    PullPage,
    PullSpec,
    PushOutcome,
    PushSpec,
)


class {class_name}(HTTPConnector):
    platform = "{platform}"
    domain = "{domain}"
    capabilities = Capabilities(pull={pull}, push={push}, incremental={incremental}, upsert={upsert})

    async def pull(self, ctx: ConnectionContext, spec: PullSpec) -> PullPage:
        raise ConnectorError("pull() not implemented — builder-agent scaffold")

    async def push(self, ctx: ConnectionContext, spec: PushSpec) -> PushOutcome:
        raise ConnectorError("push() not implemented — builder-agent scaffold")
'''


def scaffold(spec_path: Path) -> str:
    import yaml

    data = yaml.safe_load(spec_path.read_text(encoding="utf-8")) or {}
    c = data.get("connector", {})
    caps = data.get("capabilities", {}) or {}
    return _TEMPLATE.format(
        display_name=c.get("display_name", c.get("platform", "?").title()),
        status=c.get("status", "research_derived"),
        source=spec_path.name,
        class_name=c["class"],
        platform=c["platform"],
        domain=c["domain"],
        pull=bool(caps.get("pull", True)),
        push=bool(caps.get("push", True)),
        incremental=bool(caps.get("incremental", False)),
        upsert=bool(caps.get("upsert", False)),
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Connector builder agent (scaffolder)")
    parser.add_argument("spec", type=Path, help="path to a _props.<platform>.yaml file")
    args = parser.parse_args(argv)
    sys.stdout.write(scaffold(args.spec))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
