// Goals form a real tree: CXO creates only the top ("enterprise") goal. Every
// level below it — ABU, then Department, then Employee — is generated by a
// mock "agent" and approved by the role that OWNS that level, not by CXO.
// That's the point: CXO approves once (which ABUs are involved); each ABU
// Head then separately approves their own department breakdown; each Dept
// Manager then separately approves their own employee breakdown. Responsibility
// for generating/approving is distributed down the chain, not centralized at CXO.
export type GoalLevel = "enterprise" | "abu" | "dept" | "employee";

export interface Goal {
  id: string;
  parentId: string | null;
  title: string;
  description: string;
  status: "active" | "at-risk" | "planning" | "done";
  targetDate: string;
  buId: string | null; // null = enterprise-wide
  deptId?: string;      // set on dept/employee-level goals
  assigneePersonId?: string; // set on employee-level (leaf) goals
  level: GoalLevel;
  // Governs generating/approving THIS goal's own children (the next level
  // down). Undefined = nothing in flight right now — the generate control
  // stays available afterward too, so it can be re-run to add more (this is
  // a showcase demo, not a one-shot gate).
  genState?: "generating" | "awaiting-approval";
  pendingChildren?: Goal[]; // generated but not yet approved; discarded on reject
}

export const GOAL_TREE: Goal[] = [
  { id: "goal-1", parentId: null,    level: "enterprise", title: "Lift Enterprise Execution Index to 90",              description: "Composite EEI across all 5 ABUs, weighted by contribution.",                    status: "active",   targetDate: "2026-12-31", buId: null },
  { id: "goal-2", parentId: "goal-1",level: "abu",         title: "Hold Manufacturing OEE at or above 90%",             description: "Overall Equipment Effectiveness across all monitored lines.",                   status: "active",   targetDate: "2026-09-30", buId: "manufacturing" },
  { id: "goal-5", parentId: "goal-2",level: "dept",        title: "Reduce unplanned downtime below 40 hrs/quarter",    description: "Predictive maintenance coverage across all Tier-1 production lines.",           status: "at-risk",  targetDate: "2026-10-15", buId: "manufacturing", deptId: "manufacturing:maintenance" },
  { id: "goal-3", parentId: null,    level: "enterprise", title: "Cut enterprise operating cost 15% via AI workforce", description: "Reduce blended operating cost through agent-driven automation.",                status: "active",   targetDate: "2026-12-31", buId: null },
  { id: "goal-4", parentId: "goal-3",level: "abu",         title: "Zero-touch monthly financial close",                 description: "Fully automated reconciliation and cost allocation, human sign-off only.",      status: "active",   targetDate: "2026-08-31", buId: "finance" },
];

export function childrenOf(goalId: string, allGoals: Goal[]): Goal[] {
  return allGoals.filter((g) => g.parentId === goalId);
}

export function rootGoals(allGoals: Goal[]): Goal[] {
  return allGoals.filter((g) => g.parentId === null);
}
